const cardsData = [
    { title: "Ananya Chetia", description: "Vice-President", imageUrl: "https://i.postimg.cc/Bb1vMsF3/ananya.png" },
    { title: "Aryadeep Gogoi", description: "President", imageUrl: "https://res.cloudinary.com/nikks/image/upload/v1736851298/aryadeep_o2itqq.png" },
    { title: "Chetan Singh Verma", description: "General Secretary", imageUrl: "https://res.cloudinary.com/nikks/image/upload/v1736850672/chetan_xfsgyz.png" },
    { title: "Tripti Golcha", description: "Literary and PR Head", imageUrl: "https://i.postimg.cc/Y04vZYJJ/tripti.png" },
    { title: "Parismita Malakar", description: "Media and Graphics Design Head", imageUrl: "https://i.postimg.cc/SRj94wz1/parismita.png" },
    { title: "Pragyan Das", description: "Technical Head", imageUrl: "https://i.postimg.cc/W1ZMhLYQ/pragyan.png" },
    { title: "Priyam Sogani", description: "Treasurer", imageUrl: "https://i.postimg.cc/cLVGBYmv/pixelcut-export-1.png" },
    { title: "Aditi Goel", description: "Senior Executive", imageUrl: "https://i.postimg.cc/pTCQRfcr/aditi.png" },
    { title: "Jagatjyoti Deb", description: "Senior Executive", imageUrl: "https://i.postimg.cc/90fdMDsp/jagat.png" },
    { title: "Sai Smaran Aare", description: "Junior Executive", imageUrl: "https://i.postimg.cc/J4qfvvQC/sai.png" },
    { title: "Ravi Nayan", description: "Junior Executive", imageUrl: "https://i.postimg.cc/RVM87Gxs/ravi.png" },
    { title: "Aditya Sharma", description: "Junior Executive", imageUrl: "https://i.postimg.cc/JhGCbxZV/aditya.png" },
    { title: "Dubari Kalita", description: "Junior Executive", imageUrl: "https://i.postimg.cc/gkWpfvF8/dubari.png" },
    { title: "Koustubh Mishra", description: "Literary & PR Member", imageUrl: "https://i.postimg.cc/GmMVXDxF/koustubh.png" },
    { title: "Namrata Nayak", description: " Literary & PR Member", imageUrl: "https://i.postimg.cc/QVL2sZyj/namrata.png" },
    { title: "Bhabhana Das", description: "Literary & PR Member", imageUrl: "https://i.postimg.cc/pTrbJZjM/bhabhana.png" },
    { title: "Anwesh Saha", description: "Literary & PR Member", imageUrl: "https://i.postimg.cc/zDM5p9pt/anwesh.png" },
    { title: "Jitamanyu Phukan", description: "Media & Graphics Design Member", imageUrl: "https://i.postimg.cc/zGc4sWFc/jitamanyu.png" },
    { title: "Rajdeep Sarmah", description: "Media & Graphics Design Member", imageUrl: "https://i.postimg.cc/wjxn52Lx/rajdeep.png" },
    { title: "Kasish Sahu", description: "Media & Graphics Design Member", imageUrl: "https://i.postimg.cc/pX69fGnR/kasish.png" },
    { title: "Manisha Saloi", description: "Media & Graphics Design Member", imageUrl: "https://i.postimg.cc/YCw2L5W3/manisha-1.png" },
    { title: "Indranuj Dev", description: "Media & Graphics Design Member", imageUrl: "https://i.postimg.cc/Y9W87LKm/pixelcut-export.png" },
    { title: "Shashwat Patel", description: "Technical Member", imageUrl: "https://i.postimg.cc/fb0RfMQv/shashwat.png" },
    { title: "Nikhil Singh", description: "Technical Member", imageUrl: "https://i.postimg.cc/k511yd9f/nikhil-1.png" },
    { title: "Sibajit Mazumder", description: "Technical Member", imageUrl: "https://i.postimg.cc/VvMmZgt1/sibajit.png" },
    { title: "Deepanshu Sharma", description: "Technical Member", imageUrl: "https://i.postimg.cc/L6Ntr3Yb/deepanshu.png" },
    { title: "Subrata Lodh", description: "Technical Member", imageUrl: "https://i.postimg.cc/bN3rz6R1/subrata.png" },
  ];
  
  export default cardsData;
  